local isRetailWow = (WOW_PROJECT_ID == WOW_PROJECT_MAINLINE)
if isRetailWow then
local L_DR_Mouse_Over_Text = DR_Mouse_Over_Test_Localization_My_Localization_Table
Dr_Mouse_Over_Debuff_Spells = {
    --Incapacitates
    ["Sap"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Polymorph"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Polymorph: Turtle"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Polymorph: Pig"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Repentance"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Gouge"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Wyvern Sting"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Hibernate"] = L_DR_Mouse_Over_Text["Incapacitate"],
    ["Dragon's Breath"] = L_DR_Mouse_Over_Text["Incapacitate"],
    --Silences
    ["Strangulate"] = L_DR_Mouse_Over_Text["Silence"],
    ["Garrote - Silence"] = L_DR_Mouse_Over_Text["Silence"],
    ["Sigil of Silence"] = L_DR_Mouse_Over_Text["Silence"],
    ["Solar Beam"] = L_DR_Mouse_Over_Text["Silence"],
    ["Spider Sting"] = L_DR_Mouse_Over_Text["Silence"],
    ["Avenger's Shield"] = L_DR_Mouse_Over_Text["Silence"],
    ["Shield of Virtue"] = L_DR_Mouse_Over_Text["Silence"],
    ["Silence"] = L_DR_Mouse_Over_Text["Silence"],
    ["Unstable Affliction Silence Effect"] = L_DR_Mouse_Over_Text["Silence"],
    -- Stun
    ["Cheap Shot"] = L_DR_Mouse_Over_Text["Stun"],
    ["Pounce"] = L_DR_Mouse_Over_Text["Stun"],
    ["Bash"] = L_DR_Mouse_Over_Text["Stun"],
    ["Hammer of Justice"] = L_DR_Mouse_Over_Text["Stun"],
    ["Shadowfury"] = L_DR_Mouse_Over_Text["Stun"],
    ["Charge"] = L_DR_Mouse_Over_Text["Stun"],
    ["Intercept"] = L_DR_Mouse_Over_Text["Stun"],
    ["Concussion Blow"] = L_DR_Mouse_Over_Text["Stun"],
    ["War stomp"] = L_DR_Mouse_Over_Text["Stun"],
    ["Intimidation"] = L_DR_Mouse_Over_Text["Stun"],
    ["Kidney Shot"] = L_DR_Mouse_Over_Text["Stun"],
    --Disorient
    ["Blinding Sleet"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Sigil of Misery"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Cyclone"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Scare Beast"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Song of Chi-ji"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Incendiary Brew"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Blinding Light"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Turn Evil"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Mind Control"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Psychic Scream"] = L_DR_Mouse_Over_Text["Disorient"],
    ["Mind Bomb"]  = L_DR_Mouse_Over_Text["Disorient"],
    ["Blind"]    = L_DR_Mouse_Over_Text["Disorient"],
    ["Fear"]  = L_DR_Mouse_Over_Text["Disorient"],
    ["Howl of Terror"]    = L_DR_Mouse_Over_Text["Disorient"],
    ["Seduction"]  = L_DR_Mouse_Over_Text["Disorient"],
    ["Intimidating Shout"]    = L_DR_Mouse_Over_Text["Disorient"],
    ["Agent of Chaos"]  = L_DR_Mouse_Over_Text["Disorient"],
    --Root
    ["Entangling Roots"] = L_DR_Mouse_Over_Text["Root"],
    ["Frost Nova"] = L_DR_Mouse_Over_Text["Root"],
    ["Nature's Grasp"] = L_DR_Mouse_Over_Text["Root"],
    ["Deathchill"] = L_DR_Mouse_Over_Text["Root"],
    --Disarm
    ["Disarm"] = L_DR_Mouse_Over_Text["Disarm"],
    ["Dismantle"] = L_DR_Mouse_Over_Text["Disarm"],
    ["Grapple Weapon"] = L_DR_Mouse_Over_Text["Disarm"],
    --Knockback
    ["Thunderstorm"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Shining Force"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Ring of Peace"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Blast Wave"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Overrun"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Gorefiend's Grasp"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Hi-Explosive Trap"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Bursting Shot"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Mighty Ox Kick"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Fellash"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Whiplash"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Dragon Charge"] = L_DR_Mouse_Over_Text["Knockback"],
    ["Typhoon"] = L_DR_Mouse_Over_Text["Knockback"],
    --Taunt
    ["Dark Command"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Death Grip"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Torment"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Growl"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Distracting Shot"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Provoke"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Final Stand"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Hand of Reckoning"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Suffering"] = L_DR_Mouse_Over_Text["Taunt"],
    ["Taunt"] = L_DR_Mouse_Over_Text["Taunt"],
}
end