local isRetailWow = (LE_EXPANSION_LEVEL_CURRENT == LE_EXPANSION_SHADOWLANDS)
if isRetailWow then
local L = Mouseover_Tooltip_Locale_Table
Dr_Mouse_Over_Spells = {
    --Incapacitates
    [1776]    = L["Incapacitate"],    -- Gouge
    [6770]    = L["Incapacitate"],    -- Sap
    [118]     = L["Incapacitate"],    -- Polymorph
    [28271]   = L["Incapacitate"],    -- Polymorph (Turtle)
    [28272]   = L["Incapacitate"],    -- Polymorph (Pig)
    [61025]   = L["Incapacitate"],    -- Polymorph (Snake)
    [61305]   = L["Incapacitate"],    -- Polymorph (Black Cat)
    [61780]   = L["Incapacitate"],    -- Polymorph (Turkey)
    [61721]   = L["Incapacitate"],    -- Polymorph (Rabbit)
    [126819]  = L["Incapacitate"],    -- Polymorph (Porcupine)
    [161353]  = L["Incapacitate"],    -- Polymorph (Polar Bear Cub)
    [161354]  = L["Incapacitate"],    -- Polymorph (Monkey)
    [161355]  = L["Incapacitate"],    -- Polymorph (Penguin)
    [161372]  = L["Incapacitate"],    -- Polymorph (Peacock)
    [277787]  = L["Incapacitate"],    -- Polymorph (Baby Direhorn)
    [277792]  = L["Incapacitate"],    -- Polymorph (Bumblebee)
    [115078]  = L["Incapacitate"],    -- Paralysis
    [20066]   = L["Incapacitate"],    -- Repentance
    [9484]    = L["Incapacitate"],    -- Shackle Undead
    [200196]  = L["Incapacitate"],    -- Holy Word: Chastise
    [51514]   = L["Incapacitate"],    -- Hex
    [99]      = L["Incapacitate"],    -- Incapacitating Roar
    [710]     = L["Incapacitate"],    -- Banish
    [6789]    = L["Incapacitate"],    -- Mortal Coil
    [82691]   = L["Incapacitate"],    -- Ring of Frost
    [213691]  = L["Incapacitate"],    -- Scatter Shot
    [2637]    = L["Incapacitate"],    -- Hibernate
    [217832]  = L["Incapacitate"],    -- Imprison
    [3355]    = L["Incapacitate"],    -- Freezing Trap
    --Silences
    [47476]   = L["Silence"],         -- Strangulate
    [204490]  = L["Silence"],         -- Sigil of Silence
    [202933]  = L["Silence"],         -- Spider Sting
    [356727]  = L["Silence"],         -- Spider Venom
    [217824]  = L["Silence"],         -- Shield of Virtue
    [15487]   = L["Silence"],         -- Silence
    -- Stun
    [210141]  = L["Stun"],            -- Zombie Explosion
    [334693]  = L["Stun"],            -- Absolute Zero (Breath of Sindragosa)
    [108194]  = L["Stun"],            -- Asphyxiate (Unholy)
    [221562]  = L["Stun"],            -- Asphyxiate (Blood)
    [91800]   = L["Stun"],            -- Gnaw (Ghoul)
    [91797]   = L["Stun"],            -- Monstrous Blow (Mutated Ghoul)
    [287254]  = L["Stun"],            -- Dead of Winter
    [179057]  = L["Stun"],            -- Chaos Nova
    [205630]  = L["Stun"],            -- Illidan's Grasp (Primary effect)
    [208618]  = L["Stun"],            -- Illidan's Grasp (Secondary effect)
    [211881]  = L["Stun"],            -- Fel Eruption
    [200166]  = L["Stun"],            -- Metamorphosis (PvE stun effect)
    [203123]  = L["Stun"],            -- Maim
    [163505]  = L["Stun"],            -- Rake (Prowl)
    [5211]    = L["Stun"],            -- Mighty Bash
    [202244]  = L["Stun"],            -- Overrun
    [325321]  = L["Stun"],            -- Wild Hunt's Charge
    [357021]  = L["Stun"],            -- Consecutive Concussion
    [24394]   = L["Stun"],            -- Intimidation
    [119381]  = L["Stun"],            -- Leg Sweep
    [202346]  = L["Stun"],            -- Double Barrel
    [853]     = L["Stun"],            -- Hammer of Justice
    [255941]  = L["Stun"],            -- Wake of Ashes
    [64044]   = L["Stun"],            -- Psychic Horror
    [200200]  = L["Stun"],            -- Holy Word: Chastise Censure
    [1833]    = L["Stun"],            -- Cheap Shot
    [408]     = L["Stun"],            -- Kidney Shot
    [118905]  = L["Stun"],            -- Static Charge (Capacitor Totem)
    [118345]  = L["Stun"],            -- Pulverize (Primal Earth Elemental)
    [305485]  = L["Stun"],            -- Lightning Lasso
    [89766]   = L["Stun"],            -- Axe Toss
    [171017]  = L["Stun"],            -- Meteor Strike (Infernal)
    [171018]  = L["Stun"],            -- Meteor Strike (Abyssal)
    [30283]   = L["Stun"],            -- Shadowfury
    [46968]   = L["Stun"],            -- Shockwave
    [132168]  = L["Stun"],            -- Shockwave (Protection)
    [145047]  = L["Stun"],            -- Shockwave (Proving Grounds PvE)
    [132169]  = L["Stun"],            -- Storm Bolt
    [199085]  = L["Stun"],            -- Warpath
    [20549]   = L["Stun"],            -- War Stomp (Tauren)
    [255723]  = L["Stun"],            -- Bull Rush (Highmountain Tauren)
    [287712]  = L["Stun"],            -- Haymaker (Kul Tiran)
    [332423]  = L["Stun"],            -- Sparkling Driftglobe Core (Kyrian Covenant)
    --Disorient
    [207167]  = L["Disorient"],       -- Blinding Sleet
    [207685]  = L["Disorient"],       -- Sigil of Misery
    [33786]   = L["Disorient"],       -- Cyclone
    [1513]    = L["Disorient"],       -- Scare Beast
    [198909]  = L["Disorient"],       -- Song of Chi-ji
    [202274]  = L["Disorient"],       -- Incendiary Brew
    [105421]  = L["Disorient"],       -- Blinding Light
    [10326]   = L["Disorient"],       -- Turn Evil
    [605]     = L["Disorient"],       -- Mind Control
    [8122]    = L["Disorient"],       -- Psychic Scream
    [226943]  = L["Disorient"],       -- Mind Bomb
    [31661]   = L["Disorient"],       -- Dragon's Breath
    [2094]    = L["Disorient"],       -- Blind
    [118699]  = L["Disorient"],       -- Fear
    [5484]    = L["Disorient"],       -- Howl of Terror
    [6358]    = L["Disorient"],       -- Seduction (Succubus)
    [5246]    = L["Disorient"],       -- Intimidating Shout 1
    [331866]  = L["Disorient"],       -- Agent of Chaos (Venthyr Covenant)
    --Root
    [204085]  = L["Root"],            -- Deathchill (Chains of Ice)
    [233395]  = L["Root"],            -- Deathchill (Remorseless Winter)
    [339]     = L["Root"],            -- Entangling Roots
    [170855]  = L["Root"],            -- Entangling Roots (Nature's Grasp)
    [102359]  = L["Root"],            -- Mass Entanglement
    [117526]  = L["Root"],            -- Binding Shot
    [162480]  = L["Root"],            -- Steel Trap
    [273909]  = L["Root"],            -- Steelclaw Trap
    [212638]  = L["Root"],            -- Tracker's Net
    [201158]  = L["Root"],            -- Super Sticky Tar
    [122]     = L["Root"],            -- Frost Nova
    [33395]   = L["Root"],            -- Freeze
    [198121]  = L["Root"],            -- Frostbite
    [342375]  = L["Root"],            -- Tormenting Backlash (Torghast PvE)
    [233582]  = L["Root"],            -- Entrenched in Flame
    [116706]  = L["Root"],            -- Disable
    [324382]  = L["Root"],            -- Clash
    [64695]   = L["Root"],            -- Earthgrab (Totem effect)
    [285515]  = L["Root"],            -- Surge of Power
    --Disarm
    [209749]  = L["Disarm"],          -- Faerie Swarm (Balance Honor Talent)
    [207777]  = L["Disarm"],          -- Dismantle
    [233759]  = L["Disarm"],          -- Grapple Weapon
    [236077]  = L["Disarm"],          -- Disarm
    --Knockback
    [108199]  = L["Knockback"],        -- Gorefiend's Grasp
    [202249]  = L["Knockback"],        -- Overrun
    [61391]   = L["Knockback"],        -- Typhoon
    [102793]  = L["Knockback"],        -- Ursol's Vortex
    [186387]  = L["Knockback"],        -- Bursting Shot
    [236777]  = L["Knockback"],        -- Hi-Explosive Trap
    [157981]  = L["Knockback"],        -- Blast Wave
    [237371]  = L["Knockback"],        -- Ring of Peace
    [204263]  = L["Knockback"],        -- Shining Force
    [51490]   = L["Knockback"],        -- Thunderstorm
    --Taunt
    [56222]   = L["Taunt"],           -- Dark Command
    [51399]   = L["Taunt"],           -- Death Grip (Taunt Effect)
    [185245]  = L["Taunt"],           -- Torment
    [6795]    = L["Taunt"],           -- Growl (Druid)
    [2649]    = L["Taunt"],           -- Growl (Hunter Pet) (TODO: confirm)
    [20736]   = L["Taunt"],           -- Distracting Shot
    [116189]  = L["Taunt"],           -- Provoke
    [118635]  = L["Taunt"],           -- Provoke (Black Ox Statue)
    [196727]  = L["Taunt"],           -- Provoke (Niuzao)
    [204079]  = L["Taunt"],           -- Final Stand
    [62124]   = L["Taunt"],           -- Hand of Reckoning
    [17735]   = L["Taunt"],           -- Suffering (Voidwalker) (TODO: confirm)
    [355]     = L["Taunt"],           -- Taunt
}
end